package cn.lands.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

import cn.lands.model.base.BaseType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Type extends BaseType<Type> {
	public static final Type dao = new Type();
	
	public static Page<Record> paginate(int pageNum, int pageSize) {
		String select = "select *";
		String suffix = "from type";
		return Db.paginate(pageNum, pageSize, select, suffix);
	}
}
